export interface PlatformAchievement {
  id: string;
  title: string;
  desc: string;
  icon: string;
  tier: 'Bronze' | 'Silver' | 'Gold' | 'Platinum' | 'Diamond' | 'Mythic';
  category: 'quests' | 'cards' | 'forge' | 'trading' | 'arcade' | 'prestige' | 'community';
  shardsReward: number;
}

export const PLATFORM_ACHIEVEMENTS: PlatformAchievement[] = [
  // --- 🚀 Quests & Genesis (6) ---
  {
    id: 'genesis_pioneer',
    title: 'Genesis Pioneer',
    desc: 'Registered for Season 1 and activated cryogenic telemetry.',
    icon: '🚀',
    tier: 'Bronze',
    category: 'quests',
    shardsReward: 25,
  },
  {
    id: 'first_quest',
    title: 'First Quantum Pulse',
    desc: 'Complete your first daily quest on RialoTrace.',
    icon: '⚡',
    tier: 'Bronze',
    category: 'quests',
    shardsReward: 35,
  },
  {
    id: 'dedicated_runner',
    title: 'Dedicated Protocol Runner',
    desc: 'Complete 5 daily missions across Season 1 testnet.',
    icon: '🏃',
    tier: 'Silver',
    category: 'quests',
    shardsReward: 50,
  },
  {
    id: 'crypto_scholar',
    title: 'Cryptographic Scholar',
    desc: 'Answer 3 daily Web3 consensus quizzes correctly.',
    icon: '🧠',
    tier: 'Silver',
    category: 'quests',
    shardsReward: 60,
  },
  {
    id: 'streak_keeper',
    title: 'Cryo Reactor Streak',
    desc: 'Maintain a 3-day consecutive quest check-in streak.',
    icon: '📅',
    tier: 'Gold',
    category: 'quests',
    shardsReward: 90,
  },
  {
    id: 'relentless_sync',
    title: 'Relentless Synchronizer',
    desc: 'Maintain a 7-day uninterrupted quest streak on Rialo.',
    icon: '🔥',
    tier: 'Platinum',
    category: 'quests',
    shardsReward: 150,
  },

  // --- 🎴 Cards & Collecting (6) ---
  {
    id: 'rookie_cardholder',
    title: 'First Draw Initiate',
    desc: 'Acquire your first archetype card in your deck.',
    icon: '🃏',
    tier: 'Bronze',
    category: 'cards',
    shardsReward: 30,
  },
  {
    id: 'collector_apprentice',
    title: 'Cryogenic Collector',
    desc: 'Collect at least 5 unique Season 1 Archetype cards.',
    icon: '🎴',
    tier: 'Silver',
    category: 'cards',
    shardsReward: 50,
  },
  {
    id: 'deck_master',
    title: 'Deck Master',
    desc: 'Assemble 12 unique Archetype cards in your binder.',
    icon: '📚',
    tier: 'Gold',
    category: 'cards',
    shardsReward: 80,
  },
  {
    id: 'archive_curator',
    title: 'Archive Curator',
    desc: 'Collect 20 unique Archetype cards from Season 1.',
    icon: '🏛️',
    tier: 'Platinum',
    category: 'cards',
    shardsReward: 125,
  },
  {
    id: 'holo_mirage',
    title: 'Holographic Mirage',
    desc: 'Obtain a Legendary or Mythic Tier Holo card.',
    icon: '✨',
    tier: 'Diamond',
    category: 'cards',
    shardsReward: 200,
  },
  {
    id: 'omniscient_binder',
    title: 'Omniscient Binder',
    desc: 'Assemble all 30 Season 1 Archetype cards in your personal collection.',
    icon: '🌟',
    tier: 'Mythic',
    category: 'cards',
    shardsReward: 500,
  },

  // --- 🧪 The Superconducting Forge (4) ---
  {
    id: 'apprentice_melter',
    title: 'Superconducting Smelter',
    desc: 'Place duplicate cards into the Superconducting Forge.',
    icon: '🔥',
    tier: 'Bronze',
    category: 'forge',
    shardsReward: 40,
  },
  {
    id: 'forge_alchemist',
    title: 'Master Alchemist',
    desc: 'Transmute lower-grade cards into higher tier in the Forge.',
    icon: '🧪',
    tier: 'Silver',
    category: 'forge',
    shardsReward: 60,
  },
  {
    id: 'fusion_ignition',
    title: 'Reactor Critical Mass',
    desc: 'Successfully execute a High-Yield Fusion.',
    icon: '⚛️',
    tier: 'Gold',
    category: 'forge',
    shardsReward: 100,
  },
  {
    id: 'zero_resist_forge',
    title: 'Zero-Resistance Transmutation',
    desc: 'Forge an Ultra-Rare Sovereign Card with 0% dissipation.',
    icon: '⚡',
    tier: 'Diamond',
    category: 'forge',
    shardsReward: 250,
  },

  // --- 🔄 P2P Trading (4) ---
  {
    id: 'trade_broker',
    title: 'OTC Floor Trader',
    desc: 'Inspect P2P Trading Market and create a peer exchange offer.',
    icon: '🔄',
    tier: 'Bronze',
    category: 'trading',
    shardsReward: 45,
  },
  {
    id: 'liquidity_facilitator',
    title: 'Liquidity Facilitator',
    desc: 'Complete 3 successful card trade swaps with peers.',
    icon: '🤝',
    tier: 'Silver',
    category: 'trading',
    shardsReward: 65,
  },
  {
    id: 'market_arbitrageur',
    title: 'Market Arbitrageur',
    desc: 'Complete a trade swap for an in-demand rare archetype.',
    icon: '📈',
    tier: 'Gold',
    category: 'trading',
    shardsReward: 110,
  },
  {
    id: 'titan_swapper',
    title: 'Titan P2P Broker',
    desc: 'Complete 10 peer-to-peer card transfers on the decentralized board.',
    icon: '🌐',
    tier: 'Platinum',
    category: 'trading',
    shardsReward: 175,
  },

  // --- 🕹️ Meissner Arcade & Sound Lab (4) ---
  {
    id: 'arcade_ace',
    title: 'Meissner Speed Demon',
    desc: 'Fly through magnetic pillars in Zero-Friction Glide.',
    icon: '🕹️',
    tier: 'Platinum',
    category: 'arcade',
    shardsReward: 100,
  },
  {
    id: 'gravity_defier',
    title: 'Zero-G Aeronaut',
    desc: 'Score 100+ points in Zero-Friction Glide arcade challenge.',
    icon: '🚀',
    tier: 'Gold',
    category: 'arcade',
    shardsReward: 85,
  },
  {
    id: 'sound_maestro',
    title: 'Cyber DJ Virtuoso',
    desc: 'Synthesize beats using the 16-pad MPC drum machine.',
    icon: '🎹',
    tier: 'Platinum',
    category: 'arcade',
    shardsReward: 100,
  },
  {
    id: 'frequency_alchemist',
    title: 'Harmonic Resonator',
    desc: 'Record and trigger custom 16-step arpeggiator patterns.',
    icon: '🎛️',
    tier: 'Gold',
    category: 'arcade',
    shardsReward: 75,
  },

  // --- 💬 Community & Trollbox (2) ---
  {
    id: 'trollbox_vanguard',
    title: 'Trollbox Vanguard',
    desc: 'Broadcast 5 live messages to the community Trollbox channel.',
    icon: '💬',
    tier: 'Silver',
    category: 'community',
    shardsReward: 50,
  },
  {
    id: 'alpha_hunter',
    title: 'Alpha Stream Curator',
    desc: 'Engage with top community alpha posts and protocol highlights.',
    icon: '🔍',
    tier: 'Bronze',
    category: 'community',
    shardsReward: 40,
  },

  // --- 👑 Prestige & Dynamic Whitelist (4) ---
  {
    id: 'shard_tycoon',
    title: 'Superconducting Whale',
    desc: 'Amass 500+ Superconducting Shards in your personal vault.',
    icon: '💎',
    tier: 'Diamond',
    category: 'prestige',
    shardsReward: 150,
  },
  {
    id: 'millionaire_shards',
    title: 'Shard Sovereign',
    desc: 'Accumulate 1,500+ lifetime shards across testnet activities.',
    icon: '💰',
    tier: 'Mythic',
    category: 'prestige',
    shardsReward: 400,
  },
  {
    id: 'whitelist_ascendant',
    title: 'Ascendant Vanguard',
    desc: 'Rise to Top 5% on Rialo dynamic 10-tier whitelist leaderboard.',
    icon: '🛡️',
    tier: 'Platinum',
    category: 'prestige',
    shardsReward: 125,
  },
  {
    id: 'whitelist_immortal',
    title: 'Rialo Immortal Standing',
    desc: 'Reach Tier 1 Grandmaster Ascendant on the dynamic whitelist.',
    icon: '👑',
    tier: 'Mythic',
    category: 'prestige',
    shardsReward: 500,
  },
];
