import { CardArchetype } from './types';

export const RIALO_30_ARCHETYPES: Record<string, CardArchetype> = {
  pioneer: {
    id: 'pioneer',
    title: 'Ecosystem Pioneer',
    lore: 'Explores untracked block space and seeds initial liquidity protocols across new sub-second clusters.',
    rarity: 'COMMON',
    glowColor: '#6366F1',
    image: '/cards/pioneer.png',
    badgeEmoji: '🚀',
    iconBg: '#6366F1',
  },
  vanguard: {
    id: 'vanguard',
    title: 'Testnet Vanguard',
    lore: 'Commands high-throughput validator clusters, stress-testing execution boundaries with 10k TPS resilience.',
    rarity: 'RARE',
    glowColor: '#3B82F6',
    image: '/cards/vanguard.png',
    badgeEmoji: '⚡',
    iconBg: '#3B82F6',
  },
  architect: {
    id: 'architect',
    title: 'State Architecture Engineer',
    lore: 'Designs parallelized state access trees and asynchronous I/O scheduling pipelines for ultra-low latency execution.',
    rarity: 'EPIC',
    glowColor: '#10B981',
    image: '/cards/architect.png',
    badgeEmoji: '🛠️',
    iconBg: '#10B981',
  },
  sovereign: {
    id: 'sovereign',
    title: 'Parallel Sovereign',
    lore: 'Governs high-value consensus clusters, routing high-frequency DeFi transactions through sovereign pipelines.',
    rarity: 'LEGENDARY',
    glowColor: '#F59E0B',
    image: '/cards/sovereign.png',
    badgeEmoji: '👑',
    iconBg: '#F59E0B',
  },
  sentinel: {
    id: 'sentinel',
    title: 'Consensus Sentinel',
    lore: 'Guards the integrity of RialoBFT rounds, neutralizing state discrepancies with cryptographic finality proofs.',
    rarity: 'RARE',
    glowColor: '#8B5CF6',
    image: '/cards/sentinel.png',
    badgeEmoji: '🛡️',
    iconBg: '#8B5CF6',
  },
  devourer: {
    id: 'devourer',
    title: 'Sub-Second Devourer',
    lore: 'Consumes pending transaction queues at near-instant finality, leaving zero latency in block processing.',
    rarity: 'MYTHIC',
    glowColor: '#EC4899',
    image: '/cards/devourer.png',
    badgeEmoji: '👁️',
    iconBg: '#EC4899',
  },
  arbitrageur: {
    id: 'arbitrageur',
    title: 'High-Frequency Arbitrageur',
    lore: 'Executes atomic cross-pool arbitrage in single-slot transactions, balancing pricing across parallel order books.',
    rarity: 'EPIC',
    glowColor: '#14B8A6',
    image: '/cards/arbitrageur.png',
    badgeEmoji: '⚖️',
    iconBg: '#14B8A6',
  },
  finalizer: {
    id: 'finalizer',
    title: 'Sub-Second Finalizer',
    lore: 'Seals block commits with deterministic finality, locking state changes into the ledger with cryptographically unyielding certainty.',
    rarity: 'LEGENDARY',
    glowColor: '#EF4444',
    image: '/cards/finalizer.png',
    badgeEmoji: '🔒',
    iconBg: '#EF4444',
  },
  navigator: {
    id: 'navigator',
    title: 'Mempool Navigator',
    lore: 'Traverses parallel transaction streams, routing priority execution through optimized consensus paths.',
    rarity: 'COMMON',
    glowColor: '#06B6D4',
    image: '/cards/navigator.png',
    badgeEmoji: '🧭',
    iconBg: '#06B6D4',
  },
  usdc_titan: {
    id: 'usdc_titan',
    title: 'USDC Liquidity Titan',
    lore: 'Anchors deep dollar-denominated reserves, providing bedrock liquidity for high-frequency algorithmic trade execution.',
    rarity: 'RARE',
    glowColor: '#22C55E',
    image: '/cards/usdc_titan.png',
    badgeEmoji: '💵',
    iconBg: '#22C55E',
  },
  chronomancer: {
    id: 'chronomancer',
    title: 'Temporal Chronomancer',
    lore: 'Manipulates block timestamp verification, anchoring high-speed state transitions into immutable temporal order.',
    rarity: 'MYTHIC',
    glowColor: '#A855F7',
    image: '/cards/chronomancer.png',
    badgeEmoji: '⏳',
    iconBg: '#A855F7',
  },
  zk_oracle: {
    id: 'zk_oracle',
    title: 'Zero-Knowledge Oracle',
    lore: 'Generates zero-knowledge validity proofs off-chain, verifying massive batch states in single execution cycles.',
    rarity: 'LEGENDARY',
    glowColor: '#3B82F6',
    image: '/cards/zk_oracle.png',
    badgeEmoji: '🔮',
    iconBg: '#3B82F6',
  },
  hypervisor: {
    id: 'hypervisor',
    title: 'Parallel Hypervisor',
    lore: 'Orchestrates multi-threaded EVM environments, eliminating execution bottlenecks across parallel state trees.',
    rarity: 'LEGENDARY',
    glowColor: '#14B8A6',
    image: '/cards/hypervisor.png',
    badgeEmoji: '🖥️',
    iconBg: '#14B8A6',
  },
  nebula_miner: {
    id: 'nebula_miner',
    title: 'Nebula Sequencer',
    lore: 'Harvests cosmic block entropy, compiling cross-shard transactions into ultra-dense cryptographic blocks.',
    rarity: 'EPIC',
    glowColor: '#8B5CF6',
    image: '/cards/nebula_miner.png',
    badgeEmoji: '🌌',
    iconBg: '#8B5CF6',
  },
  valkyrie: {
    id: 'valkyrie',
    title: 'Sub-Second Valkyrie',
    lore: 'Flies ahead of the mempool, executing high-priority micro-transactions with surgical, zero-latency precision.',
    rarity: 'MYTHIC',
    glowColor: '#F43F5E',
    image: '/cards/valkyrie.png',
    badgeEmoji: '⚔️',
    iconBg: '#F43F5E',
  },
  cipher_blade: {
    id: 'cipher_blade',
    title: 'State Infiltrator',
    lore: 'Probes smart contracts with sub-second fuzzing algorithms, revealing state flaws before malicious actors strike.',
    rarity: 'EPIC',
    glowColor: '#10B981',
    image: '/cards/cipher_blade.png',
    badgeEmoji: '🗡️',
    iconBg: '#10B981',
  },
  solaris_priest: {
    id: 'solaris_priest',
    title: 'Solaris Validator',
    lore: 'Chunnels perpetual energy into consensus rounds, illuminating dark mempools with blinding transparency.',
    rarity: 'RARE',
    glowColor: '#F59E0B',
    image: '/cards/solaris_priest.png',
    badgeEmoji: '☀️',
    iconBg: '#F59E0B',
  },
  liquidity_siren: {
    id: 'liquidity_siren',
    title: 'Deep Pool Siren',
    lore: 'Commands multi-million dollar concentrated liquidity pools with harmonic, automated yield optimization.',
    rarity: 'LEGENDARY',
    glowColor: '#06B6D4',
    image: '/cards/liquidity_siren.png',
    badgeEmoji: '🌊',
    iconBg: '#06B6D4',
  },
  void_walker: {
    id: 'void_walker',
    title: 'Mempool Voidwalker',
    lore: 'Navigates between block proposals, absorbing transaction slippage into dark, instantaneous liquidity voids.',
    rarity: 'MYTHIC',
    glowColor: '#6366F1',
    image: '/cards/void_walker.png',
    badgeEmoji: '🌀',
    iconBg: '#6366F1',
  },
  mev_slayer: {
    id: 'mev_slayer',
    title: 'MEV Slayer',
    lore: 'Hunts extractive arbitrage bots with deterministic sandwich-defense algorithms and instant punitive slashing.',
    rarity: 'LEGENDARY',
    glowColor: '#EF4444',
    image: '/cards/mev_slayer.png',
    badgeEmoji: '🛡️',
    iconBg: '#EF4444',
  },
  synthetic_alchemist: {
    id: 'synthetic_alchemist',
    title: 'Synthetic Alchemist',
    lore: 'Transmutes raw on-chain collateral into hyper-efficient, yield-bearing native stablecoin primitives.',
    rarity: 'EPIC',
    glowColor: '#EAB308',
    image: '/cards/synthetic_alchemist.png',
    badgeEmoji: '⚗️',
    iconBg: '#EAB308',
  },
  cross_chain_courier: {
    id: 'cross_chain_courier',
    title: 'Cross-Chain Courier',
    lore: 'Dispatches high-frequency cryptographic state packets seamlessly across sovereign parallel clusters.',
    rarity: 'MYTHIC',
    glowColor: '#818CF8',
    image: '/cards/cross_chain_courier.png',
    badgeEmoji: '⚡',
    iconBg: '#818CF8',
  },
  aether_weaver: {
    id: 'aether_weaver',
    title: 'Aether Netweaver',
    lore: 'Spins synthetic state threads across orbital network nodes with zero data loss.',
    rarity: 'LEGENDARY',
    glowColor: '#EC4899',
    image: '/cards/aether_weaver.png',
    badgeEmoji: '🕸️',
    iconBg: '#EC4899',
  },
  ephemeral_runner: {
    id: 'ephemeral_runner',
    title: 'Ephemeral Speedrunner',
    lore: 'Cruises through block propagation vectors at near-light velocity on custom pulse-engine cycles.',
    rarity: 'EPIC',
    glowColor: '#06B6D4',
    image: '/cards/ephemeral_runner.png',
    badgeEmoji: '🏍️',
    iconBg: '#06B6D4',
  },
  consensus_warden: {
    id: 'consensus_warden',
    title: 'Consensus Warden',
    lore: 'Stands immovable against Byzantine fault vectors, reinforcing enclave boundaries with cybernetic armor.',
    rarity: 'RARE',
    glowColor: '#10B981',
    image: '/cards/consensus_warden.png',
    badgeEmoji: '🛡️',
    iconBg: '#10B981',
  },
  plasma_reaper: {
    id: 'plasma_reaper',
    title: 'Plasma Blade Reaper',
    lore: 'Cleaves through state congestion with dual superheated plasma edges and ruthless precision.',
    rarity: 'MYTHIC',
    glowColor: '#F43F5E',
    image: '/cards/plasma_reaper.png',
    badgeEmoji: '⚔️',
    iconBg: '#F43F5E',
  },
  celestial_envoy: {
    id: 'celestial_envoy',
    title: 'Celestial Envoy',
    lore: 'Relays orbital consensus telemetry from lunar listening posts to coordinate global validator sets.',
    rarity: 'LEGENDARY',
    glowColor: '#F59E0B',
    image: '/cards/celestial_envoy.png',
    badgeEmoji: '🌕',
    iconBg: '#F59E0B',
  },
  cyber_ronin: {
    id: 'cyber_ronin',
    title: 'Testnet Cyber Ronin',
    lore: 'A masterless warrior drifting through testnets, testing validator blades against chaotic conditions.',
    rarity: 'EPIC',
    glowColor: '#64748B',
    image: '/cards/cyber_ronin.png',
    badgeEmoji: '🗡️',
    iconBg: '#64748B',
  },
  rialo_overseer: {
    id: 'rialo_overseer',
    title: 'Rialo Grid Overseer',
    lore: 'Supreme observer perched high above the grid, orchestrating balance across all 30 protocol archetypes.',
    rarity: 'MYTHIC',
    glowColor: '#6366F1',
    image: '/cards/rialo_overseer.png',
    badgeEmoji: '👁️',
    iconBg: '#6366F1',
  },
  photon_striker: {
    id: 'photon_striker',
    title: 'Photon Striker',
    lore: 'Calibrates high-energy beam emitters from neon control decks to neutralize rogue memory leaks.',
    rarity: 'LEGENDARY',
    glowColor: '#EAB308',
    image: '/cards/photon_striker.png',
    badgeEmoji: '💥',
    iconBg: '#EAB308',
  },
};

export const ALL_30_CARDS = Object.values(RIALO_30_ARCHETYPES);
